#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

export UNITTEST_NAME=file_preload/TEST1
export UNITTEST_NUM=1

# standard unit test setup
. ../unittest/unittest.sh

require_test_type medium
require_build_type debug nondebug

setup

expect_normal_exit ../../tools/mkfs.pmemfile/mkfs.pmemfile $DIR/dummy_fs 16m

mkdir -p $DIR/dummy_mount_point

export TEST_LD_PRELOAD=libpmemfile_preload.so
export PMEMFILE_POOLS=$DIR/dummy_mount_point:$DIR/dummy_fs

export PMEMFILE_PRELOAD_LOG=pmemfile_preload.log
export INTERCEPT_LOG=intercept.log
export INTERCEPT_LOG_NO_PID=1

expect_normal_exit cp dummy_file_a $DIR/dummy_mount_point/file_a
expect_normal_exit cp dummy_file_b $DIR/dummy_mount_point/file_b
expect_normal_exit cp $DIR/dummy_mount_point/file_a file_a.log
expect_normal_exit cp $DIR/dummy_mount_point/file_b file_b.log

cmp file_a.log dummy_file_a
cmp file_b.log dummy_file_b

expect_normal_exit cat $DIR/dummy_mount_point/file_a > file_a_cat.log

cmp file_a_cat.log dummy_file_a

expect_normal_exit ls $DIR/dummy_mount_point > pmemfile_ls_root.log

cmp pmemfile_ls_root.log ls_root_expected_log

expect_normal_exit ls -o --time-style=+"" $DIR/dummy_mount_point | sed 's/\s\+/ /g' > file_preload_lsl1.log
expect_normal_exit ls -ao --time-style=+"" $DIR/dummy_mount_point | sed -e 's/\s\+/ /g' -e '/\.\./d' > file_preload_lsla1.log

check

# todo: when rm works...
# expect_normal_exit rm $DIR/dummy_mount_point/file_a
# expect_normal_exit ls $DIR/dummy_mount_point > pmemfile_ls_root_after_rm.log
# cmp pmemfile_ls_root_after_rm.log ls_root_after_rm_expected_log

pass
